### ISSUE TITLE
a problem about 'unpickle' function

### ISSUE THREAD

**Issue by caijie12138** [daib13/TwoStageVAE#1]
when I try to run the cifar10 dataset, there is a problem occurs:
Traceback (most recent call last):
  File "preprocess.py", line 190, in <module>
    preporcess_cifar10()
  File "preprocess.py", line 149, in preporcess_cifar10
    x_train = load_cifar10_data('training')
    images_array = np.concatenate(images_array, 0)
  File "preprocess.py", line 51, in load_cifar10_data
    img_dict = unpickle(filename)
NameError: name 'unpickle' is not defined

Am I miss something?

**Comment by daib13** [comment]
Hi, this is because python3 does not have the unpickle function. I will add the unpickle function in the script very soon.

**Comment by daib13** [comment]
Hi, @caijie12138 
I have updated the script and added the unpickle function for python3. I will close the issue if it works fine to you.

**Comment by caijie12138** [comment]
OK
